"""WellKOC — KOC Endpoints (Full)"""
from typing import Optional
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import get_db
from app.api.v1.deps import CurrentUser, require_role
from app.models.user import User, UserRole

router = APIRouter(prefix="/koc", tags=["KOC"])

class KOCProfileUpdate(BaseModel):
    display_name: Optional[str] = None
    bio: Optional[str] = None
    avatar_url: Optional[str] = None
    social_links: Optional[dict] = None

@router.get("/profile/{koc_id}")
async def get_koc_profile(koc_id: UUID, db: AsyncSession = Depends(get_db)):
    r = await db.execute(select(User).where(User.id == koc_id, User.role == UserRole.KOC))
    koc = r.scalar_one_or_none()
    if not koc: raise HTTPException(404, "KOC không tồn tại")
    return {"id": str(koc.id), "display_name": koc.display_name, "bio": koc.bio, "avatar_url": koc.avatar_url, "reputation_score": koc.reputation_score, "total_commission_earned": float(koc.total_commission_earned), "tier": koc.membership_tier, "referral_code": koc.referral_code}

@router.put("/profile")
async def update_koc_profile(body: KOCProfileUpdate, current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    if body.display_name: current_user.display_name = body.display_name
    if body.bio: current_user.bio = body.bio
    if body.avatar_url: current_user.avatar_url = body.avatar_url
    db.add(current_user)
    return {"status": "updated"}

@router.get("/leaderboard")
async def koc_leaderboard(limit: int = Query(50, ge=10, le=200), db: AsyncSession = Depends(get_db)):
    r = await db.execute(select(User).where(User.role == UserRole.KOC, User.is_active == True).order_by(User.total_commission_earned.desc()).limit(limit))
    kocs = r.scalars().all()
    return {"items": [{"rank": i+1, "id": str(k.id), "display_name": k.display_name, "avatar_url": k.avatar_url, "total_earned": float(k.total_commission_earned), "reputation_score": k.reputation_score} for i, k in enumerate(kocs)]}

@router.get("/affiliate-link")
async def generate_affiliate_link(product_id: UUID, current_user: User = Depends(require_role([UserRole.KOC]))):
    import hashlib
    code = hashlib.sha256(f"{current_user.id}-{product_id}".encode()).hexdigest()[:8].upper()
    return {"short_url": f"https://wkc.io/{code}", "full_url": f"https://wellkoc.com/products/{product_id}?ref={current_user.referral_code}", "short_code": code}

@router.get("/analytics")
async def koc_analytics(current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    from app.models.order import Commission, CommissionStatus
    from sqlalchemy import func
    r = await db.execute(select(func.sum(Commission.base_amount), func.count(Commission.id)).where(Commission.koc_id == current_user.id, Commission.status == CommissionStatus.SETTLED))
    gmv, orders = r.one()
    return {"gmv_total": float(gmv or 0), "orders_total": orders or 0, "commission_total": float(current_user.total_commission_earned), "reputation_score": current_user.reputation_score, "referral_code": current_user.referral_code}


# ── Affiliate Links (plural) ────────────────────────────────────────────────
class AffiliateLinkCreate(BaseModel):
    product_id: UUID

@router.get("/affiliate-links")
async def list_affiliate_links(current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    """List all affiliate links generated by this KOC."""
    # Returns links keyed by product_id from share_links table when available
    # For now returns the computed link for each product the KOC has referenced
    import hashlib
    # Basic: return a link based on referral code
    return {"items": [], "referral_code": current_user.referral_code, "base_url": f"https://wellkoc.com?ref={current_user.referral_code}"}

@router.post("/affiliate-links", status_code=201)
async def create_affiliate_link(body: AffiliateLinkCreate, current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    """Generate a short affiliate link for a specific product."""
    import hashlib
    code = hashlib.sha256(f"{current_user.id}-{body.product_id}".encode()).hexdigest()[:8].upper()
    return {
        "id": code,
        "product_id": str(body.product_id),
        "short_url": f"https://wkc.io/{code}",
        "full_url": f"https://wellkoc.com/products/{body.product_id}?ref={current_user.referral_code}",
        "short_code": code,
        "clicks": 0,
        "conversions": 0,
    }

@router.delete("/affiliate-links/{link_id}", status_code=204)
async def delete_affiliate_link(link_id: str, current_user: User = Depends(require_role([UserRole.KOC]))):
    """Delete/deactivate an affiliate link. (No-op until share_links table exists.)"""
    return


# ── Commissions ────────────────────────────────────────────────────────────
@router.get("/commissions")
async def koc_commissions(
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    status: Optional[str] = Query(None),
    current_user: User = Depends(require_role([UserRole.KOC])),
    db: AsyncSession = Depends(get_db),
):
    """List commission records for this KOC."""
    from app.models.order import Commission, CommissionStatus
    q = select(Commission).where(Commission.koc_id == current_user.id)
    if status:
        q = q.where(Commission.status == status)
    total_r = await db.execute(select(func.count()).select_from(q.subquery()))
    total = total_r.scalar() or 0
    q = q.order_by(Commission.created_at.desc()).offset((page-1)*per_page).limit(per_page)
    r = await db.execute(q)
    items = r.scalars().all()
    return {
        "items": [{"id": str(c.id), "order_id": str(c.order_id), "amount": float(c.base_amount), "status": c.status, "tier": c.tier, "created_at": c.created_at.isoformat()} for c in items],
        "total": total, "page": page,
    }


# ── Team (T2 referral tree) ─────────────────────────────────────────────────
@router.get("/team")
async def koc_team(current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    """Return direct T2 KOC members referred by this KOC."""
    r = await db.execute(select(User).where(User.referred_by_id == current_user.id, User.role == UserRole.KOC, User.is_active == True))
    team = r.scalars().all()
    return {"items": [{"id": str(m.id), "display_name": m.display_name, "avatar_url": m.avatar_url, "total_earned": float(m.total_commission_earned), "referral_code": m.referral_code} for m in team], "count": len(team)}


# ── Ranking ─────────────────────────────────────────────────────────────────
@router.get("/ranking")
async def koc_ranking(current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    """Return this KOC's current rank + pool position."""
    from app.models.pool_ranking import PoolRanking
    from datetime import date
    today = date.today()
    r = await db.execute(
        select(PoolRanking).where(PoolRanking.koc_id == current_user.id)
        .order_by(PoolRanking.year.desc(), PoolRanking.week.desc()).limit(1)
    )
    ranking = r.scalar_one_or_none()
    if not ranking:
        return {"rank": None, "pool": None, "score": 0, "commission_amount": 0}
    return {"rank": ranking.rank, "pool": ranking.pool, "score": float(ranking.score), "commission_amount": float(ranking.commission_amount), "week": ranking.week, "year": ranking.year}


# ── Payout Request ──────────────────────────────────────────────────────────
class PayoutReq(BaseModel):
    amount: float
    method: str  # "bank_transfer" | "crypto" | "wallet"

@router.post("/payout/request", status_code=201)
async def request_payout(body: PayoutReq, current_user: User = Depends(require_role([UserRole.KOC])), db: AsyncSession = Depends(get_db)):
    """Request commission payout."""
    if body.amount <= 0:
        raise HTTPException(400, "Số tiền rút phải lớn hơn 0")
    if float(current_user.total_commission_earned) < body.amount:
        raise HTTPException(400, "Số dư hoa hồng không đủ")
    # Real implementation: create payout record and trigger bank transfer
    # For now, return pending status
    import uuid as _uuid
    return {"payout_id": str(_uuid.uuid4()), "amount": body.amount, "method": body.method, "status": "pending", "message": "Yêu cầu rút tiền đã được gửi. Sẽ xử lý trong 1-3 ngày làm việc."}
